site_name: spatial-tda
site_description: A Python package for Topological Data Analysis(TDA) in spatial data.
site_author: hashansl
site_url: https://hashansl.github.io/spatial-tda
repo_url: https://github.com/hashansl/spatial-tda

copyright: "Copyright &copy; 2024 - 2024 Hashan Fernando"

theme:
    palette:
        - scheme: default
          #   primary: blue
          #   accent: indigo
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
        - scheme: slate
          primary: indigo
          accent: indigo
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
    name: material
    icon:
        repo: fontawesome/brands/github
    logo: assets/logo.png
    favicon: assets/favicon.png
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.top
        - search.highlight
        - search.share
    custom_dir: "docs/overrides"
    font:
        text: Google Sans
        code: Regular

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - git-revision-date-localized:
          enable_creation_date: true
          type: timeago
    # - pdf-export
    - mkdocs-jupyter:
          include_source: True
          ignore_h1_titles: True
          execute: True
          allow_errors: false
          ignore: ["conf.py"]
        #   execute_ignore: ["*ignore.ipynb"]
          execute_ignore: [
                    # "notebooks/00_key_features.ipynb",
                    "notebooks/01_spatial_tda_intro.ipynb",
                    "notebooks/02_adjacency_simplex.ipynb"
                    ]
          
markdown_extensions:
    - admonition
    - abbr
    - attr_list
    - def_list
    - footnotes
    - meta
    - md_in_html
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

# extra:
#     analytics:
#         provider: google
#         property: UA-XXXXXXXXX-X

nav:
    - Home: index.md
    - Installation: installation.md
    - Usage: notebooks/00_key_features.ipynb
    # - Get Started: get-started.md
    - Contributing: contributing.md
    - FAQ: faq.md
    # - Changelog: changelog.md
    - Report Issues: https://github.com/hashansl/spatial-tda/issues
    # - Examples:
        # - examples/intro.ipynb
    - API Reference:
          - AdjacencySimplex: adjacency_simplex.md
    - Notebooks:
          - notebooks/00_key_features.ipynb
          - notebooks/01_spatial_tda_intro.ipynb
          - notebooks/02_adjacency_simplex.ipynb

          
